# Environment Setup ----

# Conda Environment Setup Instructions ----
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
# 
#    conda env create -f conda_environment.yml
#    conda env update --file 000_environment_setup/01_conda_environment.yml --prune
#    conda env export --name ds4b_101p > envname.yml
#    conda env remove --name ds4b_101p
#    conda env list

name: vm_dash
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.1
  - pip
  - pip:
      # Core Data
      - numpy
      - pandas
      - statsmodels
      - scipy
      - pandas_flavor
      - plydata

      # Visualization
      - plotly

      # Excel
      - xlsxwriter
      - openpyxl

      # Apps
      - dash-bootstrap-components
      - dash-core-components
      - dash-html-components
      - dash-table
      - dash==2.3.1

      # Extending Pandas
      - json5
      - jupyterlab

      # Maps
      - geopandas

  
