version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: webserver
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /home/ec2-user/nginx.conf:/etc/nginx/nginx.conf
            - /home/ec2-user/ssl:/ssl/

    vm_dash:
        image: 685653090285.dkr.ecr.us-east-2.amazonaws.com/vm_dash:latest
        container_name: vm_dash
        restart: unless-stopped
        expose:
            - 8050