version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: webserver
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /home/ec2-user/nginx.conf:/etc/nginx/nginx.conf
            - /home/ec2-user/ssl:/ssl/
            
    vm-dash-app:
        restart: unless-stopped
        expose:
           - 8050